server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enable:
        all: true
      export:
        prometheus:
          enabled: true
          endpoint: /actuator/prometheus
    info:
      enabled: true
    env:
      enabled: true